export const CONSTANTS = Object.freeze({
	DRIVER_STATUSES: [
		"PENDING",
		"APPROVED",
		"REJECTED",
		"ACTIVE",
		"INACTIVE",
		"SUSPENDED",
	] as const,
	MERCHANT_CATEGORIES: ["ATK", "Printing", "Food"] as const,
	ORDER_STATUSES: [
		"REQUESTED",
		"MATCHING",
		"ACCEPTED",
		"PREPARING",
		"READY_FOR_PICKUP",
		"ARRIVING",
		"IN_TRIP",
		"COMPLETED",
		"CANCELLED_BY_USER",
		"CANCELLED_BY_DRIVER",
		"CANCELLED_BY_MERCHANT",
		"CANCELLED_BY_SYSTEM",
		"NO_SHOW",
	] as const,
	ORDER_TYPES: ["RIDE", "DELIVERY", "FOOD"] as const,
	COUPON_TYPES: ["GENERAL", "EVENT", "MERCHANT", "FIRST_ORDER"] as const,
	DAY_OF_WEEK: [
		"SUNDAY",
		"MONDAY",
		"TUESDAY",
		"WEDNESDAY",
		"THURSDAY",
		"FRIDAY",
		"SATURDAY",
	] as const,
	REPORT_CATEGORIES: ["BEHAVIOR", "SAFETY", "FRAUD", "OTHER"] as const,
	REPORT_STATUS: ["PENDING", "INVESTIGATING", "RESOLVED", "DISMISSED"] as const,
	REVIEW_CATEGORIES: [
		"CLEANLINESS",
		"COURTESY",
		"PUNCTUALITY",
		"SAFETY",
		"COMMUNICATION",
		"OTHER",
	] as const,
	EMERGENCY_TYPES: [
		"ACCIDENT",
		"HARASSMENT",
		"THEFT",
		"MEDICAL",
		"OTHER",
	] as const,
	EMERGENCY_STATUS: [
		"REPORTED",
		"ACKNOWLEDGED",
		"RESPONDING",
		"RESOLVED",
	] as const,
	GENERAL_RULE_TYPES: ["PERCENTAGE", "FIXED"] as const,
	USER_ROLES: ["ADMIN", "OPERATOR", "MERCHANT", "DRIVER", "USER"] as const,
	USER_GENDERS: ["MALE", "FEMALE"] as const,
	BANK_PROVIDERS: ["BCA", "BNI", "BRI", "MANDIRI", "PERMATA"] as const,
	ORDER_REJECTION_REASONS: [
		"OUT_OF_STOCK",
		"TOO_BUSY",
		"INGREDIENT_UNAVAILABLE",
		"CLOSED",
		"OTHER",
	] as const,
} as const);

export const AUTH_CONSTANTS = Object.freeze({
	SESSION_TOKEN: "AkadeMove-AMST",
	SESSION_DATA: "AkadeMove-AMSD",
	SESSION_DONT_REMEMBER: "AkadeMove-AMDR",
} as const);

export const TRANSACTION_TYPE = [
	"TOPUP",
	"WITHDRAW",
	"PAYMENT",
	"REFUND",
	"ADJUSTMENT",
	"COMMISSION",
	"EARNING",
] as const;
export const TRANSACTION_STATUS = [
	"PENDING",
	"SUCCESS",
	"FAILED",
	"CANCELLED",
	"EXPIRED",
	"REFUNDED",
] as const;
export const CURRENCY = ["IDR"] as const;
export const PAYMENT_PROVIDER = ["MIDTRANS", "MANUAL"] as const;
export const PAYMENT_METHOD = [
	"QRIS",
	// "VA",
	"BANK_TRANSFER",
	"wallet",
] as const;

export const BADGE_TYPES = [
	"ACHIEVEMENT",
	"PERFORMANCE",
	"VOLUME",
	"STREAK",
	"MILESTONE",
	"SPECIAL",
] as const;

export const BADGE_LEVELS = [
	"BRONZE",
	"SILVER",
	"GOLD",
	"PLATINUM",
	"DIAMOND",
] as const;

export const BADGE_TARGET_ROLES = ["DRIVER", "MERCHANT", "USER"] as const;
export const LEADERBOARD_PERIODS = [
	"DAILY",
	"WEEKLY",
	"MONTHLY",
	"QUARTERLY",
	"YEARLY",
	"ALL-TIME",
] as const;

export const LEADERBOARD_CATEGORIES = [
	"RATING",
	"VOLUME",
	"EARNINGS",
	"STREAK",
	"ON-TIME",
	"COMPLETION-RATE",
] as const;

export const DRIVER_QUIZ_QUESTION_TYPES = [
	"MULTIPLE_CHOICE",
	"TRUE_FALSE",
] as const;

export const DRIVER_QUIZ_QUESTION_CATEGORIES = [
	"SAFETY",
	"NAVIGATION",
	"CUSTOMER_SERVICE",
	"PLATFORM_RULES",
	"EMERGENCY_PROCEDURES",
	"VEHICLE_MAINTENANCE",
	"GENERAL",
] as const;

export const DRIVER_QUIZ_ANSWER_STATUSES = [
	"IN_PROGRESS",
	"COMPLETED",
	"PASSED",
	"FAILED",
] as const;

export const DRIVER_QUIZ_STATUSES = [
	"NOT_STARTED",
	"IN_PROGRESS",
	"PASSED",
	"FAILED",
] as const;
