/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as supportRouteRouteImport } from './routes/(support)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as supportStatusRouteImport } from './routes/(support)/status'
import { Route as supportHelpRouteImport } from './routes/(support)/help'
import { Route as supportFaqRouteImport } from './routes/(support)/faq'
import { Route as supportContactRouteImport } from './routes/(support)/contact'
import { Route as productTransportRouteImport } from './routes/(product)/transport'
import { Route as productGoodsRouteImport } from './routes/(product)/goods'
import { Route as productFoodRouteImport } from './routes/(product)/food'
import { Route as productDriverRouteImport } from './routes/(product)/driver'
import { Route as legalTermsRouteImport } from './routes/(legal)/terms'
import { Route as legalPrivacyRouteImport } from './routes/(legal)/privacy'
import { Route as legalCookiesRouteImport } from './routes/(legal)/cookies'
import { Route as legalAccountDeletionRouteImport } from './routes/(legal)/account-deletion'
import { Route as companyAboutRouteImport } from './routes/(company)/about'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as DashUserRouteRouteImport } from './routes/dash/user/route'
import { Route as DashOperatorRouteRouteImport } from './routes/dash/operator/route'
import { Route as DashMerchantRouteRouteImport } from './routes/dash/merchant/route'
import { Route as DashDriverRouteRouteImport } from './routes/dash/driver/route'
import { Route as DashAdminRouteRouteImport } from './routes/dash/admin/route'
import { Route as DashUserIndexRouteImport } from './routes/dash/user/index'
import { Route as DashOperatorIndexRouteImport } from './routes/dash/operator/index'
import { Route as DashMerchantIndexRouteImport } from './routes/dash/merchant/index'
import { Route as DashDriverIndexRouteImport } from './routes/dash/driver/index'
import { Route as DashAdminIndexRouteImport } from './routes/dash/admin/index'
import { Route as DashUserWalletRouteImport } from './routes/dash/user/wallet'
import { Route as DashUserProfileRouteImport } from './routes/dash/user/profile'
import { Route as DashUserNotificationsRouteImport } from './routes/dash/user/notifications'
import { Route as DashUserHistoryRouteImport } from './routes/dash/user/history'
import { Route as DashUserBookingsRouteImport } from './routes/dash/user/bookings'
import { Route as DashOperatorUsersRouteImport } from './routes/dash/operator/users'
import { Route as DashOperatorReportsRouteImport } from './routes/dash/operator/reports'
import { Route as DashOperatorProfileRouteImport } from './routes/dash/operator/profile'
import { Route as DashOperatorPricingRouteImport } from './routes/dash/operator/pricing'
import { Route as DashOperatorOrdersRouteImport } from './routes/dash/operator/orders'
import { Route as DashOperatorMerchantsRouteImport } from './routes/dash/operator/merchants'
import { Route as DashOperatorDriversRouteImport } from './routes/dash/operator/drivers'
import { Route as DashMerchantWalletRouteImport } from './routes/dash/merchant/wallet'
import { Route as DashMerchantSalesRouteImport } from './routes/dash/merchant/sales'
import { Route as DashMerchantProfileRouteImport } from './routes/dash/merchant/profile'
import { Route as DashMerchantOrdersRouteImport } from './routes/dash/merchant/orders'
import { Route as DashMerchantMenuRouteImport } from './routes/dash/merchant/menu'
import { Route as DashMerchantAvailabilityRouteImport } from './routes/dash/merchant/availability'
import { Route as DashDriverScheduleRouteImport } from './routes/dash/driver/schedule'
import { Route as DashDriverRatingsRouteImport } from './routes/dash/driver/ratings'
import { Route as DashDriverProfileRouteImport } from './routes/dash/driver/profile'
import { Route as DashDriverOrdersRouteImport } from './routes/dash/driver/orders'
import { Route as DashDriverEarningsRouteImport } from './routes/dash/driver/earnings'
import { Route as DashAdminUsersRouteImport } from './routes/dash/admin/users'
import { Route as DashAdminProfileRouteImport } from './routes/dash/admin/profile'
import { Route as DashAdminPricingRouteImport } from './routes/dash/admin/pricing'
import { Route as DashAdminOrdersRouteImport } from './routes/dash/admin/orders'
import { Route as DashAdminMerchantsRouteImport } from './routes/dash/admin/merchants'
import { Route as DashAdminDriversRouteImport } from './routes/dash/admin/drivers'
import { Route as DashAdminAuditRouteImport } from './routes/dash/admin/audit'
import { Route as DashAdminAnalyticsRouteImport } from './routes/dash/admin/analytics'
import { Route as authSignUpUserRouteImport } from './routes/(auth)/sign-up/user'
import { Route as authSignUpMerchantRouteImport } from './routes/(auth)/sign-up/merchant'
import { Route as authSignUpDriverRouteImport } from './routes/(auth)/sign-up/driver'
import { Route as DashOperatorCouponsIndexRouteImport } from './routes/dash/operator/coupons/index'
import { Route as DashOperatorContactsIndexRouteImport } from './routes/dash/operator/contacts/index'
import { Route as DashAdminContactsIndexRouteImport } from './routes/dash/admin/contacts/index'
import { Route as DashOperatorCouponsNewRouteImport } from './routes/dash/operator/coupons/new'
import { Route as DashOperatorContactsIdRouteImport } from './routes/dash/operator/contacts/$id'
import { Route as DashAdminContactsIdRouteImport } from './routes/dash/admin/contacts/$id'
import { Route as authSignUpDriverQuizRouteImport } from './routes/(auth)/sign-up/driver/quiz'

const supportRouteRoute = supportRouteRouteImport.update({
  id: '/(support)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const supportStatusRoute = supportStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => supportRouteRoute,
} as any)
const supportHelpRoute = supportHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => supportRouteRoute,
} as any)
const supportFaqRoute = supportFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => supportRouteRoute,
} as any)
const supportContactRoute = supportContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => supportRouteRoute,
} as any)
const productTransportRoute = productTransportRouteImport.update({
  id: '/(product)/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const productGoodsRoute = productGoodsRouteImport.update({
  id: '/(product)/goods',
  path: '/goods',
  getParentRoute: () => rootRouteImport,
} as any)
const productFoodRoute = productFoodRouteImport.update({
  id: '/(product)/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const productDriverRoute = productDriverRouteImport.update({
  id: '/(product)/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const legalTermsRoute = legalTermsRouteImport.update({
  id: '/(legal)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const legalPrivacyRoute = legalPrivacyRouteImport.update({
  id: '/(legal)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const legalCookiesRoute = legalCookiesRouteImport.update({
  id: '/(legal)/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const legalAccountDeletionRoute = legalAccountDeletionRouteImport.update({
  id: '/(legal)/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const companyAboutRoute = companyAboutRouteImport.update({
  id: '/(company)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const DashUserRouteRoute = DashUserRouteRouteImport.update({
  id: '/dash/user',
  path: '/dash/user',
  getParentRoute: () => rootRouteImport,
} as any)
const DashOperatorRouteRoute = DashOperatorRouteRouteImport.update({
  id: '/dash/operator',
  path: '/dash/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashMerchantRouteRoute = DashMerchantRouteRouteImport.update({
  id: '/dash/merchant',
  path: '/dash/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashDriverRouteRoute = DashDriverRouteRouteImport.update({
  id: '/dash/driver',
  path: '/dash/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashAdminRouteRoute = DashAdminRouteRouteImport.update({
  id: '/dash/admin',
  path: '/dash/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashUserIndexRoute = DashUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashUserRouteRoute,
} as any)
const DashOperatorIndexRoute = DashOperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashOperatorRouteRoute,
} as any)
const DashMerchantIndexRoute = DashMerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashMerchantRouteRoute,
} as any)
const DashDriverIndexRoute = DashDriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashDriverRouteRoute,
} as any)
const DashAdminIndexRoute = DashAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashAdminRouteRoute,
} as any)
const DashUserWalletRoute = DashUserWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashUserRouteRoute,
} as any)
const DashUserProfileRoute = DashUserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashUserRouteRoute,
} as any)
const DashUserNotificationsRoute = DashUserNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashUserRouteRoute,
} as any)
const DashUserHistoryRoute = DashUserHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashUserRouteRoute,
} as any)
const DashUserBookingsRoute = DashUserBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashUserRouteRoute,
} as any)
const DashOperatorUsersRoute = DashOperatorUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashOperatorRouteRoute,
} as any)
const DashOperatorReportsRoute = DashOperatorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashOperatorRouteRoute,
} as any)
const DashOperatorProfileRoute = DashOperatorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashOperatorRouteRoute,
} as any)
const DashOperatorPricingRoute = DashOperatorPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashOperatorRouteRoute,
} as any)
const DashOperatorOrdersRoute = DashOperatorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashOperatorRouteRoute,
} as any)
const DashOperatorMerchantsRoute = DashOperatorMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => DashOperatorRouteRoute,
} as any)
const DashOperatorDriversRoute = DashOperatorDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => DashOperatorRouteRoute,
} as any)
const DashMerchantWalletRoute = DashMerchantWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashMerchantRouteRoute,
} as any)
const DashMerchantSalesRoute = DashMerchantSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashMerchantRouteRoute,
} as any)
const DashMerchantProfileRoute = DashMerchantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashMerchantRouteRoute,
} as any)
const DashMerchantOrdersRoute = DashMerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashMerchantRouteRoute,
} as any)
const DashMerchantMenuRoute = DashMerchantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashMerchantRouteRoute,
} as any)
const DashMerchantAvailabilityRoute =
  DashMerchantAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => DashMerchantRouteRoute,
  } as any)
const DashDriverScheduleRoute = DashDriverScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashDriverRouteRoute,
} as any)
const DashDriverRatingsRoute = DashDriverRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => DashDriverRouteRoute,
} as any)
const DashDriverProfileRoute = DashDriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashDriverRouteRoute,
} as any)
const DashDriverOrdersRoute = DashDriverOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashDriverRouteRoute,
} as any)
const DashDriverEarningsRoute = DashDriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DashDriverRouteRoute,
} as any)
const DashAdminUsersRoute = DashAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashAdminRouteRoute,
} as any)
const DashAdminProfileRoute = DashAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashAdminRouteRoute,
} as any)
const DashAdminPricingRoute = DashAdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashAdminRouteRoute,
} as any)
const DashAdminOrdersRoute = DashAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashAdminRouteRoute,
} as any)
const DashAdminMerchantsRoute = DashAdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => DashAdminRouteRoute,
} as any)
const DashAdminDriversRoute = DashAdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => DashAdminRouteRoute,
} as any)
const DashAdminAuditRoute = DashAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashAdminRouteRoute,
} as any)
const DashAdminAnalyticsRoute = DashAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashAdminRouteRoute,
} as any)
const authSignUpUserRoute = authSignUpUserRouteImport.update({
  id: '/sign-up/user',
  path: '/sign-up/user',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpMerchantRoute = authSignUpMerchantRouteImport.update({
  id: '/sign-up/merchant',
  path: '/sign-up/merchant',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpDriverRoute = authSignUpDriverRouteImport.update({
  id: '/sign-up/driver',
  path: '/sign-up/driver',
  getParentRoute: () => authRouteRoute,
} as any)
const DashOperatorCouponsIndexRoute =
  DashOperatorCouponsIndexRouteImport.update({
    id: '/coupons/',
    path: '/coupons/',
    getParentRoute: () => DashOperatorRouteRoute,
  } as any)
const DashOperatorContactsIndexRoute =
  DashOperatorContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => DashOperatorRouteRoute,
  } as any)
const DashAdminContactsIndexRoute = DashAdminContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => DashAdminRouteRoute,
} as any)
const DashOperatorCouponsNewRoute = DashOperatorCouponsNewRouteImport.update({
  id: '/coupons/new',
  path: '/coupons/new',
  getParentRoute: () => DashOperatorRouteRoute,
} as any)
const DashOperatorContactsIdRoute = DashOperatorContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => DashOperatorRouteRoute,
} as any)
const DashAdminContactsIdRoute = DashAdminContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => DashAdminRouteRoute,
} as any)
const authSignUpDriverQuizRoute = authSignUpDriverQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => authSignUpDriverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dash/admin': typeof DashAdminRouteRouteWithChildren
  '/dash/driver': typeof DashDriverRouteRouteWithChildren
  '/dash/merchant': typeof DashMerchantRouteRouteWithChildren
  '/dash/operator': typeof DashOperatorRouteRouteWithChildren
  '/dash/user': typeof DashUserRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof companyAboutRoute
  '/account-deletion': typeof legalAccountDeletionRoute
  '/cookies': typeof legalCookiesRoute
  '/privacy': typeof legalPrivacyRoute
  '/terms': typeof legalTermsRoute
  '/driver': typeof productDriverRoute
  '/food': typeof productFoodRoute
  '/goods': typeof productGoodsRoute
  '/transport': typeof productTransportRoute
  '/contact': typeof supportContactRoute
  '/faq': typeof supportFaqRoute
  '/help': typeof supportHelpRoute
  '/status': typeof supportStatusRoute
  '/sign-up/driver': typeof authSignUpDriverRouteWithChildren
  '/sign-up/merchant': typeof authSignUpMerchantRoute
  '/sign-up/user': typeof authSignUpUserRoute
  '/dash/admin/analytics': typeof DashAdminAnalyticsRoute
  '/dash/admin/audit': typeof DashAdminAuditRoute
  '/dash/admin/drivers': typeof DashAdminDriversRoute
  '/dash/admin/merchants': typeof DashAdminMerchantsRoute
  '/dash/admin/orders': typeof DashAdminOrdersRoute
  '/dash/admin/pricing': typeof DashAdminPricingRoute
  '/dash/admin/profile': typeof DashAdminProfileRoute
  '/dash/admin/users': typeof DashAdminUsersRoute
  '/dash/driver/earnings': typeof DashDriverEarningsRoute
  '/dash/driver/orders': typeof DashDriverOrdersRoute
  '/dash/driver/profile': typeof DashDriverProfileRoute
  '/dash/driver/ratings': typeof DashDriverRatingsRoute
  '/dash/driver/schedule': typeof DashDriverScheduleRoute
  '/dash/merchant/availability': typeof DashMerchantAvailabilityRoute
  '/dash/merchant/menu': typeof DashMerchantMenuRoute
  '/dash/merchant/orders': typeof DashMerchantOrdersRoute
  '/dash/merchant/profile': typeof DashMerchantProfileRoute
  '/dash/merchant/sales': typeof DashMerchantSalesRoute
  '/dash/merchant/wallet': typeof DashMerchantWalletRoute
  '/dash/operator/drivers': typeof DashOperatorDriversRoute
  '/dash/operator/merchants': typeof DashOperatorMerchantsRoute
  '/dash/operator/orders': typeof DashOperatorOrdersRoute
  '/dash/operator/pricing': typeof DashOperatorPricingRoute
  '/dash/operator/profile': typeof DashOperatorProfileRoute
  '/dash/operator/reports': typeof DashOperatorReportsRoute
  '/dash/operator/users': typeof DashOperatorUsersRoute
  '/dash/user/bookings': typeof DashUserBookingsRoute
  '/dash/user/history': typeof DashUserHistoryRoute
  '/dash/user/notifications': typeof DashUserNotificationsRoute
  '/dash/user/profile': typeof DashUserProfileRoute
  '/dash/user/wallet': typeof DashUserWalletRoute
  '/dash/admin/': typeof DashAdminIndexRoute
  '/dash/driver/': typeof DashDriverIndexRoute
  '/dash/merchant/': typeof DashMerchantIndexRoute
  '/dash/operator/': typeof DashOperatorIndexRoute
  '/dash/user/': typeof DashUserIndexRoute
  '/sign-up/driver/quiz': typeof authSignUpDriverQuizRoute
  '/dash/admin/contacts/$id': typeof DashAdminContactsIdRoute
  '/dash/operator/contacts/$id': typeof DashOperatorContactsIdRoute
  '/dash/operator/coupons/new': typeof DashOperatorCouponsNewRoute
  '/dash/admin/contacts': typeof DashAdminContactsIndexRoute
  '/dash/operator/contacts': typeof DashOperatorContactsIndexRoute
  '/dash/operator/coupons': typeof DashOperatorCouponsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof companyAboutRoute
  '/account-deletion': typeof legalAccountDeletionRoute
  '/cookies': typeof legalCookiesRoute
  '/privacy': typeof legalPrivacyRoute
  '/terms': typeof legalTermsRoute
  '/driver': typeof productDriverRoute
  '/food': typeof productFoodRoute
  '/goods': typeof productGoodsRoute
  '/transport': typeof productTransportRoute
  '/contact': typeof supportContactRoute
  '/faq': typeof supportFaqRoute
  '/help': typeof supportHelpRoute
  '/status': typeof supportStatusRoute
  '/sign-up/driver': typeof authSignUpDriverRouteWithChildren
  '/sign-up/merchant': typeof authSignUpMerchantRoute
  '/sign-up/user': typeof authSignUpUserRoute
  '/dash/admin/analytics': typeof DashAdminAnalyticsRoute
  '/dash/admin/audit': typeof DashAdminAuditRoute
  '/dash/admin/drivers': typeof DashAdminDriversRoute
  '/dash/admin/merchants': typeof DashAdminMerchantsRoute
  '/dash/admin/orders': typeof DashAdminOrdersRoute
  '/dash/admin/pricing': typeof DashAdminPricingRoute
  '/dash/admin/profile': typeof DashAdminProfileRoute
  '/dash/admin/users': typeof DashAdminUsersRoute
  '/dash/driver/earnings': typeof DashDriverEarningsRoute
  '/dash/driver/orders': typeof DashDriverOrdersRoute
  '/dash/driver/profile': typeof DashDriverProfileRoute
  '/dash/driver/ratings': typeof DashDriverRatingsRoute
  '/dash/driver/schedule': typeof DashDriverScheduleRoute
  '/dash/merchant/availability': typeof DashMerchantAvailabilityRoute
  '/dash/merchant/menu': typeof DashMerchantMenuRoute
  '/dash/merchant/orders': typeof DashMerchantOrdersRoute
  '/dash/merchant/profile': typeof DashMerchantProfileRoute
  '/dash/merchant/sales': typeof DashMerchantSalesRoute
  '/dash/merchant/wallet': typeof DashMerchantWalletRoute
  '/dash/operator/drivers': typeof DashOperatorDriversRoute
  '/dash/operator/merchants': typeof DashOperatorMerchantsRoute
  '/dash/operator/orders': typeof DashOperatorOrdersRoute
  '/dash/operator/pricing': typeof DashOperatorPricingRoute
  '/dash/operator/profile': typeof DashOperatorProfileRoute
  '/dash/operator/reports': typeof DashOperatorReportsRoute
  '/dash/operator/users': typeof DashOperatorUsersRoute
  '/dash/user/bookings': typeof DashUserBookingsRoute
  '/dash/user/history': typeof DashUserHistoryRoute
  '/dash/user/notifications': typeof DashUserNotificationsRoute
  '/dash/user/profile': typeof DashUserProfileRoute
  '/dash/user/wallet': typeof DashUserWalletRoute
  '/dash/admin': typeof DashAdminIndexRoute
  '/dash/driver': typeof DashDriverIndexRoute
  '/dash/merchant': typeof DashMerchantIndexRoute
  '/dash/operator': typeof DashOperatorIndexRoute
  '/dash/user': typeof DashUserIndexRoute
  '/sign-up/driver/quiz': typeof authSignUpDriverQuizRoute
  '/dash/admin/contacts/$id': typeof DashAdminContactsIdRoute
  '/dash/operator/contacts/$id': typeof DashOperatorContactsIdRoute
  '/dash/operator/coupons/new': typeof DashOperatorCouponsNewRoute
  '/dash/admin/contacts': typeof DashAdminContactsIndexRoute
  '/dash/operator/contacts': typeof DashOperatorContactsIndexRoute
  '/dash/operator/coupons': typeof DashOperatorCouponsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(support)': typeof supportRouteRouteWithChildren
  '/dash/admin': typeof DashAdminRouteRouteWithChildren
  '/dash/driver': typeof DashDriverRouteRouteWithChildren
  '/dash/merchant': typeof DashMerchantRouteRouteWithChildren
  '/dash/operator': typeof DashOperatorRouteRouteWithChildren
  '/dash/user': typeof DashUserRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(company)/about': typeof companyAboutRoute
  '/(legal)/account-deletion': typeof legalAccountDeletionRoute
  '/(legal)/cookies': typeof legalCookiesRoute
  '/(legal)/privacy': typeof legalPrivacyRoute
  '/(legal)/terms': typeof legalTermsRoute
  '/(product)/driver': typeof productDriverRoute
  '/(product)/food': typeof productFoodRoute
  '/(product)/goods': typeof productGoodsRoute
  '/(product)/transport': typeof productTransportRoute
  '/(support)/contact': typeof supportContactRoute
  '/(support)/faq': typeof supportFaqRoute
  '/(support)/help': typeof supportHelpRoute
  '/(support)/status': typeof supportStatusRoute
  '/(auth)/sign-up/driver': typeof authSignUpDriverRouteWithChildren
  '/(auth)/sign-up/merchant': typeof authSignUpMerchantRoute
  '/(auth)/sign-up/user': typeof authSignUpUserRoute
  '/dash/admin/analytics': typeof DashAdminAnalyticsRoute
  '/dash/admin/audit': typeof DashAdminAuditRoute
  '/dash/admin/drivers': typeof DashAdminDriversRoute
  '/dash/admin/merchants': typeof DashAdminMerchantsRoute
  '/dash/admin/orders': typeof DashAdminOrdersRoute
  '/dash/admin/pricing': typeof DashAdminPricingRoute
  '/dash/admin/profile': typeof DashAdminProfileRoute
  '/dash/admin/users': typeof DashAdminUsersRoute
  '/dash/driver/earnings': typeof DashDriverEarningsRoute
  '/dash/driver/orders': typeof DashDriverOrdersRoute
  '/dash/driver/profile': typeof DashDriverProfileRoute
  '/dash/driver/ratings': typeof DashDriverRatingsRoute
  '/dash/driver/schedule': typeof DashDriverScheduleRoute
  '/dash/merchant/availability': typeof DashMerchantAvailabilityRoute
  '/dash/merchant/menu': typeof DashMerchantMenuRoute
  '/dash/merchant/orders': typeof DashMerchantOrdersRoute
  '/dash/merchant/profile': typeof DashMerchantProfileRoute
  '/dash/merchant/sales': typeof DashMerchantSalesRoute
  '/dash/merchant/wallet': typeof DashMerchantWalletRoute
  '/dash/operator/drivers': typeof DashOperatorDriversRoute
  '/dash/operator/merchants': typeof DashOperatorMerchantsRoute
  '/dash/operator/orders': typeof DashOperatorOrdersRoute
  '/dash/operator/pricing': typeof DashOperatorPricingRoute
  '/dash/operator/profile': typeof DashOperatorProfileRoute
  '/dash/operator/reports': typeof DashOperatorReportsRoute
  '/dash/operator/users': typeof DashOperatorUsersRoute
  '/dash/user/bookings': typeof DashUserBookingsRoute
  '/dash/user/history': typeof DashUserHistoryRoute
  '/dash/user/notifications': typeof DashUserNotificationsRoute
  '/dash/user/profile': typeof DashUserProfileRoute
  '/dash/user/wallet': typeof DashUserWalletRoute
  '/dash/admin/': typeof DashAdminIndexRoute
  '/dash/driver/': typeof DashDriverIndexRoute
  '/dash/merchant/': typeof DashMerchantIndexRoute
  '/dash/operator/': typeof DashOperatorIndexRoute
  '/dash/user/': typeof DashUserIndexRoute
  '/(auth)/sign-up/driver/quiz': typeof authSignUpDriverQuizRoute
  '/dash/admin/contacts/$id': typeof DashAdminContactsIdRoute
  '/dash/operator/contacts/$id': typeof DashOperatorContactsIdRoute
  '/dash/operator/coupons/new': typeof DashOperatorCouponsNewRoute
  '/dash/admin/contacts/': typeof DashAdminContactsIndexRoute
  '/dash/operator/contacts/': typeof DashOperatorContactsIndexRoute
  '/dash/operator/coupons/': typeof DashOperatorCouponsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dash/admin'
    | '/dash/driver'
    | '/dash/merchant'
    | '/dash/operator'
    | '/dash/user'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/about'
    | '/account-deletion'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/driver'
    | '/food'
    | '/goods'
    | '/transport'
    | '/contact'
    | '/faq'
    | '/help'
    | '/status'
    | '/sign-up/driver'
    | '/sign-up/merchant'
    | '/sign-up/user'
    | '/dash/admin/analytics'
    | '/dash/admin/audit'
    | '/dash/admin/drivers'
    | '/dash/admin/merchants'
    | '/dash/admin/orders'
    | '/dash/admin/pricing'
    | '/dash/admin/profile'
    | '/dash/admin/users'
    | '/dash/driver/earnings'
    | '/dash/driver/orders'
    | '/dash/driver/profile'
    | '/dash/driver/ratings'
    | '/dash/driver/schedule'
    | '/dash/merchant/availability'
    | '/dash/merchant/menu'
    | '/dash/merchant/orders'
    | '/dash/merchant/profile'
    | '/dash/merchant/sales'
    | '/dash/merchant/wallet'
    | '/dash/operator/drivers'
    | '/dash/operator/merchants'
    | '/dash/operator/orders'
    | '/dash/operator/pricing'
    | '/dash/operator/profile'
    | '/dash/operator/reports'
    | '/dash/operator/users'
    | '/dash/user/bookings'
    | '/dash/user/history'
    | '/dash/user/notifications'
    | '/dash/user/profile'
    | '/dash/user/wallet'
    | '/dash/admin/'
    | '/dash/driver/'
    | '/dash/merchant/'
    | '/dash/operator/'
    | '/dash/user/'
    | '/sign-up/driver/quiz'
    | '/dash/admin/contacts/$id'
    | '/dash/operator/contacts/$id'
    | '/dash/operator/coupons/new'
    | '/dash/admin/contacts'
    | '/dash/operator/contacts'
    | '/dash/operator/coupons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/about'
    | '/account-deletion'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/driver'
    | '/food'
    | '/goods'
    | '/transport'
    | '/contact'
    | '/faq'
    | '/help'
    | '/status'
    | '/sign-up/driver'
    | '/sign-up/merchant'
    | '/sign-up/user'
    | '/dash/admin/analytics'
    | '/dash/admin/audit'
    | '/dash/admin/drivers'
    | '/dash/admin/merchants'
    | '/dash/admin/orders'
    | '/dash/admin/pricing'
    | '/dash/admin/profile'
    | '/dash/admin/users'
    | '/dash/driver/earnings'
    | '/dash/driver/orders'
    | '/dash/driver/profile'
    | '/dash/driver/ratings'
    | '/dash/driver/schedule'
    | '/dash/merchant/availability'
    | '/dash/merchant/menu'
    | '/dash/merchant/orders'
    | '/dash/merchant/profile'
    | '/dash/merchant/sales'
    | '/dash/merchant/wallet'
    | '/dash/operator/drivers'
    | '/dash/operator/merchants'
    | '/dash/operator/orders'
    | '/dash/operator/pricing'
    | '/dash/operator/profile'
    | '/dash/operator/reports'
    | '/dash/operator/users'
    | '/dash/user/bookings'
    | '/dash/user/history'
    | '/dash/user/notifications'
    | '/dash/user/profile'
    | '/dash/user/wallet'
    | '/dash/admin'
    | '/dash/driver'
    | '/dash/merchant'
    | '/dash/operator'
    | '/dash/user'
    | '/sign-up/driver/quiz'
    | '/dash/admin/contacts/$id'
    | '/dash/operator/contacts/$id'
    | '/dash/operator/coupons/new'
    | '/dash/admin/contacts'
    | '/dash/operator/contacts'
    | '/dash/operator/coupons'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(support)'
    | '/dash/admin'
    | '/dash/driver'
    | '/dash/merchant'
    | '/dash/operator'
    | '/dash/user'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(company)/about'
    | '/(legal)/account-deletion'
    | '/(legal)/cookies'
    | '/(legal)/privacy'
    | '/(legal)/terms'
    | '/(product)/driver'
    | '/(product)/food'
    | '/(product)/goods'
    | '/(product)/transport'
    | '/(support)/contact'
    | '/(support)/faq'
    | '/(support)/help'
    | '/(support)/status'
    | '/(auth)/sign-up/driver'
    | '/(auth)/sign-up/merchant'
    | '/(auth)/sign-up/user'
    | '/dash/admin/analytics'
    | '/dash/admin/audit'
    | '/dash/admin/drivers'
    | '/dash/admin/merchants'
    | '/dash/admin/orders'
    | '/dash/admin/pricing'
    | '/dash/admin/profile'
    | '/dash/admin/users'
    | '/dash/driver/earnings'
    | '/dash/driver/orders'
    | '/dash/driver/profile'
    | '/dash/driver/ratings'
    | '/dash/driver/schedule'
    | '/dash/merchant/availability'
    | '/dash/merchant/menu'
    | '/dash/merchant/orders'
    | '/dash/merchant/profile'
    | '/dash/merchant/sales'
    | '/dash/merchant/wallet'
    | '/dash/operator/drivers'
    | '/dash/operator/merchants'
    | '/dash/operator/orders'
    | '/dash/operator/pricing'
    | '/dash/operator/profile'
    | '/dash/operator/reports'
    | '/dash/operator/users'
    | '/dash/user/bookings'
    | '/dash/user/history'
    | '/dash/user/notifications'
    | '/dash/user/profile'
    | '/dash/user/wallet'
    | '/dash/admin/'
    | '/dash/driver/'
    | '/dash/merchant/'
    | '/dash/operator/'
    | '/dash/user/'
    | '/(auth)/sign-up/driver/quiz'
    | '/dash/admin/contacts/$id'
    | '/dash/operator/contacts/$id'
    | '/dash/operator/coupons/new'
    | '/dash/admin/contacts/'
    | '/dash/operator/contacts/'
    | '/dash/operator/coupons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  supportRouteRoute: typeof supportRouteRouteWithChildren
  DashAdminRouteRoute: typeof DashAdminRouteRouteWithChildren
  DashDriverRouteRoute: typeof DashDriverRouteRouteWithChildren
  DashMerchantRouteRoute: typeof DashMerchantRouteRouteWithChildren
  DashOperatorRouteRoute: typeof DashOperatorRouteRouteWithChildren
  DashUserRouteRoute: typeof DashUserRouteRouteWithChildren
  companyAboutRoute: typeof companyAboutRoute
  legalAccountDeletionRoute: typeof legalAccountDeletionRoute
  legalCookiesRoute: typeof legalCookiesRoute
  legalPrivacyRoute: typeof legalPrivacyRoute
  legalTermsRoute: typeof legalTermsRoute
  productDriverRoute: typeof productDriverRoute
  productFoodRoute: typeof productFoodRoute
  productGoodsRoute: typeof productGoodsRoute
  productTransportRoute: typeof productTransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(support)': {
      id: '/(support)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof supportRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(support)/status': {
      id: '/(support)/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof supportStatusRouteImport
      parentRoute: typeof supportRouteRoute
    }
    '/(support)/help': {
      id: '/(support)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof supportHelpRouteImport
      parentRoute: typeof supportRouteRoute
    }
    '/(support)/faq': {
      id: '/(support)/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof supportFaqRouteImport
      parentRoute: typeof supportRouteRoute
    }
    '/(support)/contact': {
      id: '/(support)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof supportContactRouteImport
      parentRoute: typeof supportRouteRoute
    }
    '/(product)/transport': {
      id: '/(product)/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof productTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(product)/goods': {
      id: '/(product)/goods'
      path: '/goods'
      fullPath: '/goods'
      preLoaderRoute: typeof productGoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(product)/food': {
      id: '/(product)/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof productFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(product)/driver': {
      id: '/(product)/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof productDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/terms': {
      id: '/(legal)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/privacy': {
      id: '/(legal)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/cookies': {
      id: '/(legal)/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof legalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/account-deletion': {
      id: '/(legal)/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof legalAccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(company)/about': {
      id: '/(company)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof companyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/dash/user': {
      id: '/dash/user'
      path: '/dash/user'
      fullPath: '/dash/user'
      preLoaderRoute: typeof DashUserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/operator': {
      id: '/dash/operator'
      path: '/dash/operator'
      fullPath: '/dash/operator'
      preLoaderRoute: typeof DashOperatorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/merchant': {
      id: '/dash/merchant'
      path: '/dash/merchant'
      fullPath: '/dash/merchant'
      preLoaderRoute: typeof DashMerchantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/driver': {
      id: '/dash/driver'
      path: '/dash/driver'
      fullPath: '/dash/driver'
      preLoaderRoute: typeof DashDriverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/admin': {
      id: '/dash/admin'
      path: '/dash/admin'
      fullPath: '/dash/admin'
      preLoaderRoute: typeof DashAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/user/': {
      id: '/dash/user/'
      path: '/'
      fullPath: '/dash/user/'
      preLoaderRoute: typeof DashUserIndexRouteImport
      parentRoute: typeof DashUserRouteRoute
    }
    '/dash/operator/': {
      id: '/dash/operator/'
      path: '/'
      fullPath: '/dash/operator/'
      preLoaderRoute: typeof DashOperatorIndexRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/merchant/': {
      id: '/dash/merchant/'
      path: '/'
      fullPath: '/dash/merchant/'
      preLoaderRoute: typeof DashMerchantIndexRouteImport
      parentRoute: typeof DashMerchantRouteRoute
    }
    '/dash/driver/': {
      id: '/dash/driver/'
      path: '/'
      fullPath: '/dash/driver/'
      preLoaderRoute: typeof DashDriverIndexRouteImport
      parentRoute: typeof DashDriverRouteRoute
    }
    '/dash/admin/': {
      id: '/dash/admin/'
      path: '/'
      fullPath: '/dash/admin/'
      preLoaderRoute: typeof DashAdminIndexRouteImport
      parentRoute: typeof DashAdminRouteRoute
    }
    '/dash/user/wallet': {
      id: '/dash/user/wallet'
      path: '/wallet'
      fullPath: '/dash/user/wallet'
      preLoaderRoute: typeof DashUserWalletRouteImport
      parentRoute: typeof DashUserRouteRoute
    }
    '/dash/user/profile': {
      id: '/dash/user/profile'
      path: '/profile'
      fullPath: '/dash/user/profile'
      preLoaderRoute: typeof DashUserProfileRouteImport
      parentRoute: typeof DashUserRouteRoute
    }
    '/dash/user/notifications': {
      id: '/dash/user/notifications'
      path: '/notifications'
      fullPath: '/dash/user/notifications'
      preLoaderRoute: typeof DashUserNotificationsRouteImport
      parentRoute: typeof DashUserRouteRoute
    }
    '/dash/user/history': {
      id: '/dash/user/history'
      path: '/history'
      fullPath: '/dash/user/history'
      preLoaderRoute: typeof DashUserHistoryRouteImport
      parentRoute: typeof DashUserRouteRoute
    }
    '/dash/user/bookings': {
      id: '/dash/user/bookings'
      path: '/bookings'
      fullPath: '/dash/user/bookings'
      preLoaderRoute: typeof DashUserBookingsRouteImport
      parentRoute: typeof DashUserRouteRoute
    }
    '/dash/operator/users': {
      id: '/dash/operator/users'
      path: '/users'
      fullPath: '/dash/operator/users'
      preLoaderRoute: typeof DashOperatorUsersRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/operator/reports': {
      id: '/dash/operator/reports'
      path: '/reports'
      fullPath: '/dash/operator/reports'
      preLoaderRoute: typeof DashOperatorReportsRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/operator/profile': {
      id: '/dash/operator/profile'
      path: '/profile'
      fullPath: '/dash/operator/profile'
      preLoaderRoute: typeof DashOperatorProfileRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/operator/pricing': {
      id: '/dash/operator/pricing'
      path: '/pricing'
      fullPath: '/dash/operator/pricing'
      preLoaderRoute: typeof DashOperatorPricingRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/operator/orders': {
      id: '/dash/operator/orders'
      path: '/orders'
      fullPath: '/dash/operator/orders'
      preLoaderRoute: typeof DashOperatorOrdersRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/operator/merchants': {
      id: '/dash/operator/merchants'
      path: '/merchants'
      fullPath: '/dash/operator/merchants'
      preLoaderRoute: typeof DashOperatorMerchantsRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/operator/drivers': {
      id: '/dash/operator/drivers'
      path: '/drivers'
      fullPath: '/dash/operator/drivers'
      preLoaderRoute: typeof DashOperatorDriversRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/merchant/wallet': {
      id: '/dash/merchant/wallet'
      path: '/wallet'
      fullPath: '/dash/merchant/wallet'
      preLoaderRoute: typeof DashMerchantWalletRouteImport
      parentRoute: typeof DashMerchantRouteRoute
    }
    '/dash/merchant/sales': {
      id: '/dash/merchant/sales'
      path: '/sales'
      fullPath: '/dash/merchant/sales'
      preLoaderRoute: typeof DashMerchantSalesRouteImport
      parentRoute: typeof DashMerchantRouteRoute
    }
    '/dash/merchant/profile': {
      id: '/dash/merchant/profile'
      path: '/profile'
      fullPath: '/dash/merchant/profile'
      preLoaderRoute: typeof DashMerchantProfileRouteImport
      parentRoute: typeof DashMerchantRouteRoute
    }
    '/dash/merchant/orders': {
      id: '/dash/merchant/orders'
      path: '/orders'
      fullPath: '/dash/merchant/orders'
      preLoaderRoute: typeof DashMerchantOrdersRouteImport
      parentRoute: typeof DashMerchantRouteRoute
    }
    '/dash/merchant/menu': {
      id: '/dash/merchant/menu'
      path: '/menu'
      fullPath: '/dash/merchant/menu'
      preLoaderRoute: typeof DashMerchantMenuRouteImport
      parentRoute: typeof DashMerchantRouteRoute
    }
    '/dash/merchant/availability': {
      id: '/dash/merchant/availability'
      path: '/availability'
      fullPath: '/dash/merchant/availability'
      preLoaderRoute: typeof DashMerchantAvailabilityRouteImport
      parentRoute: typeof DashMerchantRouteRoute
    }
    '/dash/driver/schedule': {
      id: '/dash/driver/schedule'
      path: '/schedule'
      fullPath: '/dash/driver/schedule'
      preLoaderRoute: typeof DashDriverScheduleRouteImport
      parentRoute: typeof DashDriverRouteRoute
    }
    '/dash/driver/ratings': {
      id: '/dash/driver/ratings'
      path: '/ratings'
      fullPath: '/dash/driver/ratings'
      preLoaderRoute: typeof DashDriverRatingsRouteImport
      parentRoute: typeof DashDriverRouteRoute
    }
    '/dash/driver/profile': {
      id: '/dash/driver/profile'
      path: '/profile'
      fullPath: '/dash/driver/profile'
      preLoaderRoute: typeof DashDriverProfileRouteImport
      parentRoute: typeof DashDriverRouteRoute
    }
    '/dash/driver/orders': {
      id: '/dash/driver/orders'
      path: '/orders'
      fullPath: '/dash/driver/orders'
      preLoaderRoute: typeof DashDriverOrdersRouteImport
      parentRoute: typeof DashDriverRouteRoute
    }
    '/dash/driver/earnings': {
      id: '/dash/driver/earnings'
      path: '/earnings'
      fullPath: '/dash/driver/earnings'
      preLoaderRoute: typeof DashDriverEarningsRouteImport
      parentRoute: typeof DashDriverRouteRoute
    }
    '/dash/admin/users': {
      id: '/dash/admin/users'
      path: '/users'
      fullPath: '/dash/admin/users'
      preLoaderRoute: typeof DashAdminUsersRouteImport
      parentRoute: typeof DashAdminRouteRoute
    }
    '/dash/admin/profile': {
      id: '/dash/admin/profile'
      path: '/profile'
      fullPath: '/dash/admin/profile'
      preLoaderRoute: typeof DashAdminProfileRouteImport
      parentRoute: typeof DashAdminRouteRoute
    }
    '/dash/admin/pricing': {
      id: '/dash/admin/pricing'
      path: '/pricing'
      fullPath: '/dash/admin/pricing'
      preLoaderRoute: typeof DashAdminPricingRouteImport
      parentRoute: typeof DashAdminRouteRoute
    }
    '/dash/admin/orders': {
      id: '/dash/admin/orders'
      path: '/orders'
      fullPath: '/dash/admin/orders'
      preLoaderRoute: typeof DashAdminOrdersRouteImport
      parentRoute: typeof DashAdminRouteRoute
    }
    '/dash/admin/merchants': {
      id: '/dash/admin/merchants'
      path: '/merchants'
      fullPath: '/dash/admin/merchants'
      preLoaderRoute: typeof DashAdminMerchantsRouteImport
      parentRoute: typeof DashAdminRouteRoute
    }
    '/dash/admin/drivers': {
      id: '/dash/admin/drivers'
      path: '/drivers'
      fullPath: '/dash/admin/drivers'
      preLoaderRoute: typeof DashAdminDriversRouteImport
      parentRoute: typeof DashAdminRouteRoute
    }
    '/dash/admin/audit': {
      id: '/dash/admin/audit'
      path: '/audit'
      fullPath: '/dash/admin/audit'
      preLoaderRoute: typeof DashAdminAuditRouteImport
      parentRoute: typeof DashAdminRouteRoute
    }
    '/dash/admin/analytics': {
      id: '/dash/admin/analytics'
      path: '/analytics'
      fullPath: '/dash/admin/analytics'
      preLoaderRoute: typeof DashAdminAnalyticsRouteImport
      parentRoute: typeof DashAdminRouteRoute
    }
    '/(auth)/sign-up/user': {
      id: '/(auth)/sign-up/user'
      path: '/sign-up/user'
      fullPath: '/sign-up/user'
      preLoaderRoute: typeof authSignUpUserRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up/merchant': {
      id: '/(auth)/sign-up/merchant'
      path: '/sign-up/merchant'
      fullPath: '/sign-up/merchant'
      preLoaderRoute: typeof authSignUpMerchantRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up/driver': {
      id: '/(auth)/sign-up/driver'
      path: '/sign-up/driver'
      fullPath: '/sign-up/driver'
      preLoaderRoute: typeof authSignUpDriverRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/dash/operator/coupons/': {
      id: '/dash/operator/coupons/'
      path: '/coupons'
      fullPath: '/dash/operator/coupons'
      preLoaderRoute: typeof DashOperatorCouponsIndexRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/operator/contacts/': {
      id: '/dash/operator/contacts/'
      path: '/contacts'
      fullPath: '/dash/operator/contacts'
      preLoaderRoute: typeof DashOperatorContactsIndexRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/admin/contacts/': {
      id: '/dash/admin/contacts/'
      path: '/contacts'
      fullPath: '/dash/admin/contacts'
      preLoaderRoute: typeof DashAdminContactsIndexRouteImport
      parentRoute: typeof DashAdminRouteRoute
    }
    '/dash/operator/coupons/new': {
      id: '/dash/operator/coupons/new'
      path: '/coupons/new'
      fullPath: '/dash/operator/coupons/new'
      preLoaderRoute: typeof DashOperatorCouponsNewRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/operator/contacts/$id': {
      id: '/dash/operator/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/dash/operator/contacts/$id'
      preLoaderRoute: typeof DashOperatorContactsIdRouteImport
      parentRoute: typeof DashOperatorRouteRoute
    }
    '/dash/admin/contacts/$id': {
      id: '/dash/admin/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/dash/admin/contacts/$id'
      preLoaderRoute: typeof DashAdminContactsIdRouteImport
      parentRoute: typeof DashAdminRouteRoute
    }
    '/(auth)/sign-up/driver/quiz': {
      id: '/(auth)/sign-up/driver/quiz'
      path: '/quiz'
      fullPath: '/sign-up/driver/quiz'
      preLoaderRoute: typeof authSignUpDriverQuizRouteImport
      parentRoute: typeof authSignUpDriverRoute
    }
  }
}

interface authSignUpDriverRouteChildren {
  authSignUpDriverQuizRoute: typeof authSignUpDriverQuizRoute
}

const authSignUpDriverRouteChildren: authSignUpDriverRouteChildren = {
  authSignUpDriverQuizRoute: authSignUpDriverQuizRoute,
}

const authSignUpDriverRouteWithChildren =
  authSignUpDriverRoute._addFileChildren(authSignUpDriverRouteChildren)

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpDriverRoute: typeof authSignUpDriverRouteWithChildren
  authSignUpMerchantRoute: typeof authSignUpMerchantRoute
  authSignUpUserRoute: typeof authSignUpUserRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpDriverRoute: authSignUpDriverRouteWithChildren,
  authSignUpMerchantRoute: authSignUpMerchantRoute,
  authSignUpUserRoute: authSignUpUserRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface supportRouteRouteChildren {
  supportContactRoute: typeof supportContactRoute
  supportFaqRoute: typeof supportFaqRoute
  supportHelpRoute: typeof supportHelpRoute
  supportStatusRoute: typeof supportStatusRoute
}

const supportRouteRouteChildren: supportRouteRouteChildren = {
  supportContactRoute: supportContactRoute,
  supportFaqRoute: supportFaqRoute,
  supportHelpRoute: supportHelpRoute,
  supportStatusRoute: supportStatusRoute,
}

const supportRouteRouteWithChildren = supportRouteRoute._addFileChildren(
  supportRouteRouteChildren,
)

interface DashAdminRouteRouteChildren {
  DashAdminAnalyticsRoute: typeof DashAdminAnalyticsRoute
  DashAdminAuditRoute: typeof DashAdminAuditRoute
  DashAdminDriversRoute: typeof DashAdminDriversRoute
  DashAdminMerchantsRoute: typeof DashAdminMerchantsRoute
  DashAdminOrdersRoute: typeof DashAdminOrdersRoute
  DashAdminPricingRoute: typeof DashAdminPricingRoute
  DashAdminProfileRoute: typeof DashAdminProfileRoute
  DashAdminUsersRoute: typeof DashAdminUsersRoute
  DashAdminIndexRoute: typeof DashAdminIndexRoute
  DashAdminContactsIdRoute: typeof DashAdminContactsIdRoute
  DashAdminContactsIndexRoute: typeof DashAdminContactsIndexRoute
}

const DashAdminRouteRouteChildren: DashAdminRouteRouteChildren = {
  DashAdminAnalyticsRoute: DashAdminAnalyticsRoute,
  DashAdminAuditRoute: DashAdminAuditRoute,
  DashAdminDriversRoute: DashAdminDriversRoute,
  DashAdminMerchantsRoute: DashAdminMerchantsRoute,
  DashAdminOrdersRoute: DashAdminOrdersRoute,
  DashAdminPricingRoute: DashAdminPricingRoute,
  DashAdminProfileRoute: DashAdminProfileRoute,
  DashAdminUsersRoute: DashAdminUsersRoute,
  DashAdminIndexRoute: DashAdminIndexRoute,
  DashAdminContactsIdRoute: DashAdminContactsIdRoute,
  DashAdminContactsIndexRoute: DashAdminContactsIndexRoute,
}

const DashAdminRouteRouteWithChildren = DashAdminRouteRoute._addFileChildren(
  DashAdminRouteRouteChildren,
)

interface DashDriverRouteRouteChildren {
  DashDriverEarningsRoute: typeof DashDriverEarningsRoute
  DashDriverOrdersRoute: typeof DashDriverOrdersRoute
  DashDriverProfileRoute: typeof DashDriverProfileRoute
  DashDriverRatingsRoute: typeof DashDriverRatingsRoute
  DashDriverScheduleRoute: typeof DashDriverScheduleRoute
  DashDriverIndexRoute: typeof DashDriverIndexRoute
}

const DashDriverRouteRouteChildren: DashDriverRouteRouteChildren = {
  DashDriverEarningsRoute: DashDriverEarningsRoute,
  DashDriverOrdersRoute: DashDriverOrdersRoute,
  DashDriverProfileRoute: DashDriverProfileRoute,
  DashDriverRatingsRoute: DashDriverRatingsRoute,
  DashDriverScheduleRoute: DashDriverScheduleRoute,
  DashDriverIndexRoute: DashDriverIndexRoute,
}

const DashDriverRouteRouteWithChildren = DashDriverRouteRoute._addFileChildren(
  DashDriverRouteRouteChildren,
)

interface DashMerchantRouteRouteChildren {
  DashMerchantAvailabilityRoute: typeof DashMerchantAvailabilityRoute
  DashMerchantMenuRoute: typeof DashMerchantMenuRoute
  DashMerchantOrdersRoute: typeof DashMerchantOrdersRoute
  DashMerchantProfileRoute: typeof DashMerchantProfileRoute
  DashMerchantSalesRoute: typeof DashMerchantSalesRoute
  DashMerchantWalletRoute: typeof DashMerchantWalletRoute
  DashMerchantIndexRoute: typeof DashMerchantIndexRoute
}

const DashMerchantRouteRouteChildren: DashMerchantRouteRouteChildren = {
  DashMerchantAvailabilityRoute: DashMerchantAvailabilityRoute,
  DashMerchantMenuRoute: DashMerchantMenuRoute,
  DashMerchantOrdersRoute: DashMerchantOrdersRoute,
  DashMerchantProfileRoute: DashMerchantProfileRoute,
  DashMerchantSalesRoute: DashMerchantSalesRoute,
  DashMerchantWalletRoute: DashMerchantWalletRoute,
  DashMerchantIndexRoute: DashMerchantIndexRoute,
}

const DashMerchantRouteRouteWithChildren =
  DashMerchantRouteRoute._addFileChildren(DashMerchantRouteRouteChildren)

interface DashOperatorRouteRouteChildren {
  DashOperatorDriversRoute: typeof DashOperatorDriversRoute
  DashOperatorMerchantsRoute: typeof DashOperatorMerchantsRoute
  DashOperatorOrdersRoute: typeof DashOperatorOrdersRoute
  DashOperatorPricingRoute: typeof DashOperatorPricingRoute
  DashOperatorProfileRoute: typeof DashOperatorProfileRoute
  DashOperatorReportsRoute: typeof DashOperatorReportsRoute
  DashOperatorUsersRoute: typeof DashOperatorUsersRoute
  DashOperatorIndexRoute: typeof DashOperatorIndexRoute
  DashOperatorContactsIdRoute: typeof DashOperatorContactsIdRoute
  DashOperatorCouponsNewRoute: typeof DashOperatorCouponsNewRoute
  DashOperatorContactsIndexRoute: typeof DashOperatorContactsIndexRoute
  DashOperatorCouponsIndexRoute: typeof DashOperatorCouponsIndexRoute
}

const DashOperatorRouteRouteChildren: DashOperatorRouteRouteChildren = {
  DashOperatorDriversRoute: DashOperatorDriversRoute,
  DashOperatorMerchantsRoute: DashOperatorMerchantsRoute,
  DashOperatorOrdersRoute: DashOperatorOrdersRoute,
  DashOperatorPricingRoute: DashOperatorPricingRoute,
  DashOperatorProfileRoute: DashOperatorProfileRoute,
  DashOperatorReportsRoute: DashOperatorReportsRoute,
  DashOperatorUsersRoute: DashOperatorUsersRoute,
  DashOperatorIndexRoute: DashOperatorIndexRoute,
  DashOperatorContactsIdRoute: DashOperatorContactsIdRoute,
  DashOperatorCouponsNewRoute: DashOperatorCouponsNewRoute,
  DashOperatorContactsIndexRoute: DashOperatorContactsIndexRoute,
  DashOperatorCouponsIndexRoute: DashOperatorCouponsIndexRoute,
}

const DashOperatorRouteRouteWithChildren =
  DashOperatorRouteRoute._addFileChildren(DashOperatorRouteRouteChildren)

interface DashUserRouteRouteChildren {
  DashUserBookingsRoute: typeof DashUserBookingsRoute
  DashUserHistoryRoute: typeof DashUserHistoryRoute
  DashUserNotificationsRoute: typeof DashUserNotificationsRoute
  DashUserProfileRoute: typeof DashUserProfileRoute
  DashUserWalletRoute: typeof DashUserWalletRoute
  DashUserIndexRoute: typeof DashUserIndexRoute
}

const DashUserRouteRouteChildren: DashUserRouteRouteChildren = {
  DashUserBookingsRoute: DashUserBookingsRoute,
  DashUserHistoryRoute: DashUserHistoryRoute,
  DashUserNotificationsRoute: DashUserNotificationsRoute,
  DashUserProfileRoute: DashUserProfileRoute,
  DashUserWalletRoute: DashUserWalletRoute,
  DashUserIndexRoute: DashUserIndexRoute,
}

const DashUserRouteRouteWithChildren = DashUserRouteRoute._addFileChildren(
  DashUserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  supportRouteRoute: supportRouteRouteWithChildren,
  DashAdminRouteRoute: DashAdminRouteRouteWithChildren,
  DashDriverRouteRoute: DashDriverRouteRouteWithChildren,
  DashMerchantRouteRoute: DashMerchantRouteRouteWithChildren,
  DashOperatorRouteRoute: DashOperatorRouteRouteWithChildren,
  DashUserRouteRoute: DashUserRouteRouteWithChildren,
  companyAboutRoute: companyAboutRoute,
  legalAccountDeletionRoute: legalAccountDeletionRoute,
  legalCookiesRoute: legalCookiesRoute,
  legalPrivacyRoute: legalPrivacyRoute,
  legalTermsRoute: legalTermsRoute,
  productDriverRoute: productDriverRoute,
  productFoodRoute: productFoodRoute,
  productGoodsRoute: productGoodsRoute,
  productTransportRoute: productTransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
