include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    no_literal_bool_comparisons: ignore
  exclude:
    - lib/l10n/gen/*
linter:
  rules:
    public_member_api_docs: false
    use_null_aware_elements: true
