// This file is auto-generated by @hey-api/openapi-ts

/**
 * Location
 */
export type Location = {
	lat: number;
	lng: number;
};

/**
 * Driver
 */
export type Driver = {
	id: string;
	userId: string;
	studentId: string;
	licenseNumber: string;
	status:
		| "pending"
		| "approved"
		| "rejected"
		| "active"
		| "inactive"
		| "suspended";
	rating: number;
	isOnline?: boolean;
	currentLocation: Location | null;
	lastLocationUpdate: number | null;
	/**
	 * unix timestamp format
	 */
	createdAt: number;
};

/**
 * FailedResponse
 */
export type FailedResponse = {
	success: false;
	message: string;
	errors: Array<string>;
};

/**
 * Merchant
 */
export type Merchant = {
	id: string;
	userId: string;
	type: "merchant" | "tenant";
	name: string;
	address: string;
	location: Location | null;
	isActive?: boolean;
	rating: number;
	/**
	 * unix timestamp format
	 */
	createdAt: number;
	/**
	 * unix timestamp format
	 */
	updatedAt: number;
};

/**
 * Order
 */
export type Order = {
	id: string;
	userId: string;
	driverId: string | null;
	merchantId: string | null;
	type: "ride" | "delivery" | "food";
	status:
		| "requested"
		| "matching"
		| "accepted"
		| "arriving"
		| "in_trip"
		| "completed"
		| "cancelled_by_user"
		| "cancelled_by_driver"
		| "cancelled_by_system";
	pickupLocation: Location;
	dropoffLocation: Location;
	distanceKm: number;
	basePrice: number;
	tip?: number;
	totalPrice: number;
	note: {
		pickup?: string;
		dropoff?: string;
	} | null;
	/**
	 * unix timestamp format
	 */
	requestedAt: number;
	acceptedAt: number | null;
	arrivedAt: number | null;
	/**
	 * unix timestamp format
	 */
	createdAt: number;
	/**
	 * unix timestamp format
	 */
	updatedAt: number;
};

/**
 * Time
 */
export type Time = {
	h: number;
	m: number;
};

/**
 * Schedule
 */
export type Schedule = {
	id: string;
	driverId: string;
	dayOfWeek:
		| "sunday"
		| "monday"
		| "tuesday"
		| "wednesday"
		| "thursday"
		| "friday"
		| "saturday";
	startTime: Time;
	endTime: Time;
	isRecurring?: boolean;
	specificDate: number | null;
	isActive?: boolean;
	/**
	 * unix timestamp format
	 */
	createdAt: number;
	/**
	 * unix timestamp format
	 */
	updatedAt: number;
};

/**
 * Promo
 */
export type Promo = {
	id: string;
	name: string;
	code: string;
	rules: unknown;
	discountAmount: number;
	discountPercentage: number;
	minOrderAmount: number;
	maxOrderAmount: number;
	usageLimit: number;
	usedCount: number;
	/**
	 * unix timestamp format
	 */
	periodStart: number;
	/**
	 * unix timestamp format
	 */
	periodEnd: number;
	isActive: boolean;
	createdById: string;
	/**
	 * unix timestamp format
	 */
	createdAt: number;
};

/**
 * Report
 */
export type Report = {
	id: string;
	orderId: string | null;
	reporterId: string;
	targetUserId: string;
	category: "behavior" | "safety" | "fraud" | "other";
	description: string;
	evidenceUrl: string | null;
	status?: "pending" | "investigating" | "resolved" | "dismissed";
	handledById: string | null;
	resolution: string | null;
	/**
	 * unix timestamp format
	 */
	reportedAt: number;
	resolvedAt: number | null;
};

/**
 * Review
 */
export type Review = {
	id: string;
	orderId: string;
	fromUserId: string;
	toUserId: string;
	category?: "cleanliness" | "courtesy" | "other";
	score: number;
	comment?: string;
	/**
	 * unix timestamp format
	 */
	createdAt: number;
};

export type UuidParam = string;

export type GetQuery = boolean;

export type GetAllDriverData = {
	body?: never;
	path?: never;
	query: {
		cursor?: string;
		page: number;
		limit: number;
	};
	url: "/drivers";
};

export type GetAllDriverErrors = {
	/**
	 * Driver not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetAllDriverError = GetAllDriverErrors[keyof GetAllDriverErrors];

export type GetAllDriverResponses = {
	/**
	 * GetAllDriverSuccessResponse
	 * List of driver
	 */
	200: {
		success: true;
		message: string;
		data: Array<Driver>;
	};
};

export type GetAllDriverResponse =
	GetAllDriverResponses[keyof GetAllDriverResponses];

export type CreateDriverData = {
	body?: {
		studentId: string;
		licenseNumber: string;
	};
	path?: never;
	query?: never;
	url: "/drivers";
};

export type CreateDriverErrors = {
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type CreateDriverError = CreateDriverErrors[keyof CreateDriverErrors];

export type CreateDriverResponses = {
	/**
	 * CreateDriverSuccessResponse
	 * Create driver success
	 */
	200: {
		success: true;
		message: string;
		data: Driver;
	};
};

export type CreateDriverResponse =
	CreateDriverResponses[keyof CreateDriverResponses];

export type DeleteDriverData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/drivers/{id}";
};

export type DeleteDriverErrors = {
	/**
	 * Driver not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type DeleteDriverError = DeleteDriverErrors[keyof DeleteDriverErrors];

export type DeleteDriverResponses = {
	/**
	 * DeleteDriverSuccessResponse
	 * Delete driver success
	 */
	200: {
		success: true;
		message: string;
		data: null;
	};
};

export type DeleteDriverResponse =
	DeleteDriverResponses[keyof DeleteDriverResponses];

export type GetDriverByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query: {
		fromCache: boolean;
	};
	url: "/drivers/{id}";
};

export type GetDriverByIdErrors = {
	/**
	 * Driver not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetDriverByIdError = GetDriverByIdErrors[keyof GetDriverByIdErrors];

export type GetDriverByIdResponses = {
	/**
	 * GetDriverByIdSuccessResponse
	 * Get driver by id success
	 */
	200: {
		success: true;
		message: string;
		data: Driver;
	};
};

export type GetDriverByIdResponse =
	GetDriverByIdResponses[keyof GetDriverByIdResponses];

export type UpdateDriverData = {
	body?: {
		studentId?: string;
		licenseNumber?: string;
		status?:
			| "pending"
			| "approved"
			| "rejected"
			| "active"
			| "inactive"
			| "suspended";
		isOnline?: boolean;
		currentLocation?: Location | null;
	};
	path: {
		id: string;
	};
	query?: never;
	url: "/drivers/{id}";
};

export type UpdateDriverErrors = {
	/**
	 * Driver not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type UpdateDriverError = UpdateDriverErrors[keyof UpdateDriverErrors];

export type UpdateDriverResponses = {
	/**
	 * UpdateDriverSuccessResponse
	 * Update driver success
	 */
	200: {
		success: true;
		message: string;
		data: Driver;
	};
};

export type UpdateDriverResponse =
	UpdateDriverResponses[keyof UpdateDriverResponses];

export type GetAllMerchantData = {
	body?: never;
	path?: never;
	query: {
		cursor?: string;
		page: number;
		limit: number;
	};
	url: "/merchants";
};

export type GetAllMerchantErrors = {
	/**
	 * Merchant not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetAllMerchantError =
	GetAllMerchantErrors[keyof GetAllMerchantErrors];

export type GetAllMerchantResponses = {
	/**
	 * GetAllMerchantSuccessResponse
	 * List of merchant
	 */
	200: {
		success: true;
		message: string;
		data: Array<Merchant>;
	};
};

export type GetAllMerchantResponse =
	GetAllMerchantResponses[keyof GetAllMerchantResponses];

export type CreateMerchantData = {
	body?: {
		type: "merchant" | "tenant";
		name: string;
		address: string;
		location: Location | null;
		isActive?: boolean;
	};
	path?: never;
	query?: never;
	url: "/merchants";
};

export type CreateMerchantErrors = {
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type CreateMerchantError =
	CreateMerchantErrors[keyof CreateMerchantErrors];

export type CreateMerchantResponses = {
	/**
	 * CreateMerchantSuccessResponse
	 * Create merchant success
	 */
	200: {
		success: true;
		message: string;
		data: Merchant;
	};
};

export type CreateMerchantResponse =
	CreateMerchantResponses[keyof CreateMerchantResponses];

export type DeleteMerchantData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/merchants/{id}";
};

export type DeleteMerchantErrors = {
	/**
	 * Merchant not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type DeleteMerchantError =
	DeleteMerchantErrors[keyof DeleteMerchantErrors];

export type DeleteMerchantResponses = {
	/**
	 * DeleteMerchantSuccessResponse
	 * Delete merchant success
	 */
	200: {
		success: true;
		message: string;
		data: null;
	};
};

export type DeleteMerchantResponse =
	DeleteMerchantResponses[keyof DeleteMerchantResponses];

export type GetMerchantByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query: {
		fromCache: boolean;
	};
	url: "/merchants/{id}";
};

export type GetMerchantByIdErrors = {
	/**
	 * Merchant not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetMerchantByIdError =
	GetMerchantByIdErrors[keyof GetMerchantByIdErrors];

export type GetMerchantByIdResponses = {
	/**
	 * GetMerchantByIdSuccessResponse
	 * Get merchant by id success
	 */
	200: {
		success: true;
		message: string;
		data: Merchant;
	};
};

export type GetMerchantByIdResponse =
	GetMerchantByIdResponses[keyof GetMerchantByIdResponses];

export type UpdateMerchantData = {
	body?: {
		type: "merchant" | "tenant";
		name: string;
		address: string;
		location: Location | null;
		isActive?: boolean;
	};
	path: {
		id: string;
	};
	query?: never;
	url: "/merchants/{id}";
};

export type UpdateMerchantErrors = {
	/**
	 * Merchant not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type UpdateMerchantError =
	UpdateMerchantErrors[keyof UpdateMerchantErrors];

export type UpdateMerchantResponses = {
	/**
	 * UpdateMerchantSuccessResponse
	 * Update merchant success
	 */
	200: {
		success: true;
		message: string;
		data: Merchant;
	};
};

export type UpdateMerchantResponse =
	UpdateMerchantResponses[keyof UpdateMerchantResponses];

export type GetAllOrderData = {
	body?: never;
	path?: never;
	query: {
		cursor?: string;
		page: number;
		limit: number;
	};
	url: "/orders";
};

export type GetAllOrderErrors = {
	/**
	 * Order not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetAllOrderError = GetAllOrderErrors[keyof GetAllOrderErrors];

export type GetAllOrderResponses = {
	/**
	 * GetAllOrderSuccessResponse
	 * List of order
	 */
	200: {
		success: true;
		message: string;
		data: Array<Order>;
	};
};

export type GetAllOrderResponse =
	GetAllOrderResponses[keyof GetAllOrderResponses];

export type CreateOrderData = {
	body?: {
		userId: string;
		driverId: string | null;
		merchantId: string | null;
		type: "ride" | "delivery" | "food";
		status:
			| "requested"
			| "matching"
			| "accepted"
			| "arriving"
			| "in_trip"
			| "completed"
			| "cancelled_by_user"
			| "cancelled_by_driver"
			| "cancelled_by_system";
		pickupLocation: Location;
		dropoffLocation: Location;
		distanceKm: number;
		basePrice: number;
		tip?: number;
		totalPrice: number;
		note: {
			pickup?: string;
			dropoff?: string;
		} | null;
	};
	path?: never;
	query?: never;
	url: "/orders";
};

export type CreateOrderErrors = {
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type CreateOrderError = CreateOrderErrors[keyof CreateOrderErrors];

export type CreateOrderResponses = {
	/**
	 * CreateOrderSuccessResponse
	 * Create order success
	 */
	200: {
		success: true;
		message: string;
		data: Order;
	};
};

export type CreateOrderResponse =
	CreateOrderResponses[keyof CreateOrderResponses];

export type DeleteOrderData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/orders/{id}";
};

export type DeleteOrderErrors = {
	/**
	 * Order not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type DeleteOrderError = DeleteOrderErrors[keyof DeleteOrderErrors];

export type DeleteOrderResponses = {
	/**
	 * DeleteOrderSuccessResponse
	 * Delete order success
	 */
	200: {
		success: true;
		message: string;
		data: null;
	};
};

export type DeleteOrderResponse =
	DeleteOrderResponses[keyof DeleteOrderResponses];

export type GetOrderByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query: {
		fromCache: boolean;
	};
	url: "/orders/{id}";
};

export type GetOrderByIdErrors = {
	/**
	 * Order not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetOrderByIdError = GetOrderByIdErrors[keyof GetOrderByIdErrors];

export type GetOrderByIdResponses = {
	/**
	 * GetOrderByIdSuccessResponse
	 * Get order by id success
	 */
	200: {
		success: true;
		message: string;
		data: Order;
	};
};

export type GetOrderByIdResponse =
	GetOrderByIdResponses[keyof GetOrderByIdResponses];

export type UpdateOrderData = {
	body?: {
		driverId: string | null;
		merchantId: string | null;
		type: "ride" | "delivery" | "food";
		status:
			| "requested"
			| "matching"
			| "accepted"
			| "arriving"
			| "in_trip"
			| "completed"
			| "cancelled_by_user"
			| "cancelled_by_driver"
			| "cancelled_by_system";
		distanceKm: number;
		tip?: number;
		totalPrice: number;
		note: {
			pickup?: string;
			dropoff?: string;
		} | null;
	};
	path: {
		id: string;
	};
	query?: never;
	url: "/orders/{id}";
};

export type UpdateOrderErrors = {
	/**
	 * Order not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type UpdateOrderError = UpdateOrderErrors[keyof UpdateOrderErrors];

export type UpdateOrderResponses = {
	/**
	 * UpdateOrderSuccessResponse
	 * Update order success
	 */
	200: {
		success: true;
		message: string;
		data: Order;
	};
};

export type UpdateOrderResponse =
	UpdateOrderResponses[keyof UpdateOrderResponses];

export type GetAllScheduleData = {
	body?: never;
	path?: never;
	query: {
		cursor?: string;
		page: number;
		limit: number;
	};
	url: "/schedules";
};

export type GetAllScheduleErrors = {
	/**
	 * Schedule not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetAllScheduleError =
	GetAllScheduleErrors[keyof GetAllScheduleErrors];

export type GetAllScheduleResponses = {
	/**
	 * GetAllScheduleSuccessResponse
	 * List of schedule
	 */
	200: {
		success: true;
		message: string;
		data: Array<Schedule>;
	};
};

export type GetAllScheduleResponse =
	GetAllScheduleResponses[keyof GetAllScheduleResponses];

export type CreateScheduleData = {
	body?: {
		driverId: string;
		dayOfWeek:
			| "sunday"
			| "monday"
			| "tuesday"
			| "wednesday"
			| "thursday"
			| "friday"
			| "saturday";
		startTime: Time;
		endTime: Time;
		isRecurring?: boolean;
		specificDate: number | null;
		isActive?: boolean;
	};
	path?: never;
	query?: never;
	url: "/schedules";
};

export type CreateScheduleErrors = {
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type CreateScheduleError =
	CreateScheduleErrors[keyof CreateScheduleErrors];

export type CreateScheduleResponses = {
	/**
	 * CreateScheduleSuccessResponse
	 * Create schedule success
	 */
	200: {
		success: true;
		message: string;
		data: Schedule;
	};
};

export type CreateScheduleResponse =
	CreateScheduleResponses[keyof CreateScheduleResponses];

export type DeleteScheduleData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/schedules/{id}";
};

export type DeleteScheduleErrors = {
	/**
	 * Schedule not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type DeleteScheduleError =
	DeleteScheduleErrors[keyof DeleteScheduleErrors];

export type DeleteScheduleResponses = {
	/**
	 * DeleteScheduleSuccessResponse
	 * Delete schedule success
	 */
	200: {
		success: true;
		message: string;
		data: null;
	};
};

export type DeleteScheduleResponse =
	DeleteScheduleResponses[keyof DeleteScheduleResponses];

export type GetScheduleByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query: {
		fromCache: boolean;
	};
	url: "/schedules/{id}";
};

export type GetScheduleByIdErrors = {
	/**
	 * Schedule not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetScheduleByIdError =
	GetScheduleByIdErrors[keyof GetScheduleByIdErrors];

export type GetScheduleByIdResponses = {
	/**
	 * GetScheduleByIdSuccessResponse
	 * Get schedule by id success
	 */
	200: {
		success: true;
		message: string;
		data: Schedule;
	};
};

export type GetScheduleByIdResponse =
	GetScheduleByIdResponses[keyof GetScheduleByIdResponses];

export type UpdateScheduleData = {
	body?: {
		dayOfWeek:
			| "sunday"
			| "monday"
			| "tuesday"
			| "wednesday"
			| "thursday"
			| "friday"
			| "saturday";
		startTime: Time;
		endTime: Time;
		isRecurring?: boolean;
		specificDate: number | null;
		isActive?: boolean;
	};
	path: {
		id: string;
	};
	query?: never;
	url: "/schedules/{id}";
};

export type UpdateScheduleErrors = {
	/**
	 * Schedule not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type UpdateScheduleError =
	UpdateScheduleErrors[keyof UpdateScheduleErrors];

export type UpdateScheduleResponses = {
	/**
	 * UpdateScheduleSuccessResponse
	 * Update schedule success
	 */
	200: {
		success: true;
		message: string;
		data: Schedule;
	};
};

export type UpdateScheduleResponse =
	UpdateScheduleResponses[keyof UpdateScheduleResponses];

export type GetAllPromoData = {
	body?: never;
	path?: never;
	query: {
		cursor?: string;
		page: number;
		limit: number;
	};
	url: "/promos";
};

export type GetAllPromoErrors = {
	/**
	 * Promo not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetAllPromoError = GetAllPromoErrors[keyof GetAllPromoErrors];

export type GetAllPromoResponses = {
	/**
	 * GetAllPromoSuccessResponse
	 * List of promo
	 */
	200: {
		success: true;
		message: string;
		data: Array<Promo>;
	};
};

export type GetAllPromoResponse =
	GetAllPromoResponses[keyof GetAllPromoResponses];

export type CreatePromoData = {
	body?: {
		name: string;
		code: string;
		rules: unknown;
		discountAmount: number;
		discountPercentage: number;
		minOrderAmount: number;
		maxOrderAmount: number;
		usageLimit: number;
		/**
		 * unix timestamp format
		 */
		periodStart: number;
		/**
		 * unix timestamp format
		 */
		periodEnd: number;
		isActive: boolean;
		createdById: string;
	};
	path?: never;
	query?: never;
	url: "/promos";
};

export type CreatePromoErrors = {
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type CreatePromoError = CreatePromoErrors[keyof CreatePromoErrors];

export type CreatePromoResponses = {
	/**
	 * CreatePromoSuccessResponse
	 * Create promo success
	 */
	200: {
		success: true;
		message: string;
		data: Promo;
	};
};

export type CreatePromoResponse =
	CreatePromoResponses[keyof CreatePromoResponses];

export type DeletePromoData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/promos/{id}";
};

export type DeletePromoErrors = {
	/**
	 * Promo not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type DeletePromoError = DeletePromoErrors[keyof DeletePromoErrors];

export type DeletePromoResponses = {
	/**
	 * DeletePromoSuccessResponse
	 * Delete promo success
	 */
	200: {
		success: true;
		message: string;
		data: null;
	};
};

export type DeletePromoResponse =
	DeletePromoResponses[keyof DeletePromoResponses];

export type GetPromoByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query: {
		fromCache: boolean;
	};
	url: "/promos/{id}";
};

export type GetPromoByIdErrors = {
	/**
	 * Promo not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetPromoByIdError = GetPromoByIdErrors[keyof GetPromoByIdErrors];

export type GetPromoByIdResponses = {
	/**
	 * GetPromoByIdSuccessResponse
	 * Get promo by id success
	 */
	200: {
		success: true;
		message: string;
		data: Promo;
	};
};

export type GetPromoByIdResponse =
	GetPromoByIdResponses[keyof GetPromoByIdResponses];

export type UpdatePromoData = {
	body?: {
		name: string;
		code: string;
		rules: unknown;
		discountAmount: number;
		discountPercentage: number;
		minOrderAmount: number;
		maxOrderAmount: number;
		usageLimit: number;
		/**
		 * unix timestamp format
		 */
		periodStart: number;
		/**
		 * unix timestamp format
		 */
		periodEnd: number;
		isActive: boolean;
		createdById: string;
	};
	path: {
		id: string;
	};
	query?: never;
	url: "/promos/{id}";
};

export type UpdatePromoErrors = {
	/**
	 * Promo not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type UpdatePromoError = UpdatePromoErrors[keyof UpdatePromoErrors];

export type UpdatePromoResponses = {
	/**
	 * UpdatePromoSuccessResponse
	 * Update promo success
	 */
	200: {
		success: true;
		message: string;
		data: Promo;
	};
};

export type UpdatePromoResponse =
	UpdatePromoResponses[keyof UpdatePromoResponses];

export type GetAllReportData = {
	body?: never;
	path?: never;
	query: {
		cursor?: string;
		page: number;
		limit: number;
	};
	url: "/reports";
};

export type GetAllReportErrors = {
	/**
	 * Report not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetAllReportError = GetAllReportErrors[keyof GetAllReportErrors];

export type GetAllReportResponses = {
	/**
	 * GetAllReportSuccessResponse
	 * List of report
	 */
	200: {
		success: true;
		message: string;
		data: Array<Report>;
	};
};

export type GetAllReportResponse =
	GetAllReportResponses[keyof GetAllReportResponses];

export type CreateReportData = {
	body?: {
		orderId: string | null;
		reporterId: string;
		targetUserId: string;
		category: "behavior" | "safety" | "fraud" | "other";
		description: string;
		evidenceUrl: string | null;
		status?: "pending" | "investigating" | "resolved" | "dismissed";
		handledById: string | null;
		resolution: string | null;
	};
	path?: never;
	query?: never;
	url: "/reports";
};

export type CreateReportErrors = {
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type CreateReportError = CreateReportErrors[keyof CreateReportErrors];

export type CreateReportResponses = {
	/**
	 * CreateReportSuccessResponse
	 * Create report success
	 */
	200: {
		success: true;
		message: string;
		data: Report;
	};
};

export type CreateReportResponse =
	CreateReportResponses[keyof CreateReportResponses];

export type DeleteReportData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/reports/{id}";
};

export type DeleteReportErrors = {
	/**
	 * Report not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type DeleteReportError = DeleteReportErrors[keyof DeleteReportErrors];

export type DeleteReportResponses = {
	/**
	 * DeleteReportSuccessResponse
	 * Delete report success
	 */
	200: {
		success: true;
		message: string;
		data: null;
	};
};

export type DeleteReportResponse =
	DeleteReportResponses[keyof DeleteReportResponses];

export type GetReportByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query: {
		fromCache: boolean;
	};
	url: "/reports/{id}";
};

export type GetReportByIdErrors = {
	/**
	 * Report not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetReportByIdError = GetReportByIdErrors[keyof GetReportByIdErrors];

export type GetReportByIdResponses = {
	/**
	 * GetReportByIdSuccessResponse
	 * Get report by id success
	 */
	200: {
		success: true;
		message: string;
		data: Report;
	};
};

export type GetReportByIdResponse =
	GetReportByIdResponses[keyof GetReportByIdResponses];

export type UpdateReportData = {
	body?: {
		orderId: string | null;
		reporterId: string;
		targetUserId: string;
		category: "behavior" | "safety" | "fraud" | "other";
		description: string;
		evidenceUrl: string | null;
		status?: "pending" | "investigating" | "resolved" | "dismissed";
		handledById: string | null;
		resolution: string | null;
	};
	path: {
		id: string;
	};
	query?: never;
	url: "/reports/{id}";
};

export type UpdateReportErrors = {
	/**
	 * Report not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type UpdateReportError = UpdateReportErrors[keyof UpdateReportErrors];

export type UpdateReportResponses = {
	/**
	 * UpdateReportSuccessResponse
	 * Update report success
	 */
	200: {
		success: true;
		message: string;
		data: Report;
	};
};

export type UpdateReportResponse =
	UpdateReportResponses[keyof UpdateReportResponses];

export type GetAllReviewData = {
	body?: never;
	path?: never;
	query: {
		cursor?: string;
		page: number;
		limit: number;
	};
	url: "/review";
};

export type GetAllReviewErrors = {
	/**
	 * Review not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetAllReviewError = GetAllReviewErrors[keyof GetAllReviewErrors];

export type GetAllReviewResponses = {
	/**
	 * GetAllReviewSuccessResponse
	 * List of review
	 */
	200: {
		success: true;
		message: string;
		data: Array<Review>;
	};
};

export type GetAllReviewResponse =
	GetAllReviewResponses[keyof GetAllReviewResponses];

export type CreateReviewData = {
	body?: {
		orderId: string;
		fromUserId: string;
		toUserId: string;
		category?: "cleanliness" | "courtesy" | "other";
		score: number;
		comment?: string;
	};
	path?: never;
	query?: never;
	url: "/review";
};

export type CreateReviewErrors = {
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type CreateReviewError = CreateReviewErrors[keyof CreateReviewErrors];

export type CreateReviewResponses = {
	/**
	 * CreateReviewSuccessResponse
	 * Create review success
	 */
	200: {
		success: true;
		message: string;
		data: Review;
	};
};

export type CreateReviewResponse =
	CreateReviewResponses[keyof CreateReviewResponses];

export type DeleteReviewData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/review/{id}";
};

export type DeleteReviewErrors = {
	/**
	 * Review not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type DeleteReviewError = DeleteReviewErrors[keyof DeleteReviewErrors];

export type DeleteReviewResponses = {
	/**
	 * DeleteReviewSuccessResponse
	 * Delete review success
	 */
	200: {
		success: true;
		message: string;
		data: null;
	};
};

export type DeleteReviewResponse =
	DeleteReviewResponses[keyof DeleteReviewResponses];

export type GetReviewByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query: {
		fromCache: boolean;
	};
	url: "/review/{id}";
};

export type GetReviewByIdErrors = {
	/**
	 * Review not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type GetReviewByIdError = GetReviewByIdErrors[keyof GetReviewByIdErrors];

export type GetReviewByIdResponses = {
	/**
	 * GetReviewByIdSuccessResponse
	 * Get review by id success
	 */
	200: {
		success: true;
		message: string;
		data: Review;
	};
};

export type GetReviewByIdResponse =
	GetReviewByIdResponses[keyof GetReviewByIdResponses];

export type UpdateReviewData = {
	body?: {
		orderId: string;
		fromUserId: string;
		toUserId: string;
		category?: "cleanliness" | "courtesy" | "other";
		score: number;
		comment?: string;
	};
	path: {
		id: string;
	};
	query?: never;
	url: "/review/{id}";
};

export type UpdateReviewErrors = {
	/**
	 * Review not found
	 */
	404: FailedResponse;
	/**
	 * Internal server error
	 */
	500: FailedResponse;
};

export type UpdateReviewError = UpdateReviewErrors[keyof UpdateReviewErrors];

export type UpdateReviewResponses = {
	/**
	 * UpdateReviewSuccessResponse
	 * Update review success
	 */
	200: {
		success: true;
		message: string;
		data: Review;
	};
};

export type UpdateReviewResponse =
	UpdateReviewResponses[keyof UpdateReviewResponses];

export type ClientOptions = {
	baseUrl: "https://akademove-server.zenta.dev" | (string & {});
};
